repos:
-   repo: https://github.com/mgedmin/check-python-versions
    rev: 0.19.1
    hooks:
    -   id: check-python-versions
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-bugbear==20.1.4
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
