language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

install:
  - pip install -U pip
  - pip install -e .
  - pip install coveralls pytest pytest-cov

script: pytest --cov-report html --cov=src/Products/ZopeTree

after_success:
  - coveralls
