language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U pip
  - pip install -e .
  - pip install coveralls

script: pytest --cov-report html --cov=src/Products/ZopeTree

after_success:
  - coveralls
